# the two root directories to take the data from and to store the data in
source: /scratch/SCRATCH_SAS/roman/GraphPLI/glycowork_4_350/resources
prots:
  features:
    method: rinerator # rinerator, distance, esm
drugs:
  node_feats: glycan # IUPAC, label, onehot, glycan
split_data:
  method: random # custom, random, drug, target
  mode: inter  # drug, target, inter
  file: splits/R/inter.tsv
parse_dataset:
  filtering: all
  threshold: 1.075
