# the two root directories to take the data from and to store the data in
source: ./prebuild/structmodel/resources  # or ./prebuild/leor/resources
prots:
  features:
    method: rinerator # rinerator, distance, esm
drugs:
  node_feats: IUPAC # IUPAC, label, onehot, glycan
split_data:
  method: target # random, drug, target
