# the two root directories to take the data from and to store the data in
source: /scratch/SCRATCH_SAS/roman/GraphPLI/unilectin/resources
prots:
  features:
    method: rinerator # rinerator, distance, esm
drugs:
  node_feats: glycan # IUPAC, label, onehot, glycan
split_data:
  method: random # custom, random, drug, target
  train: 0
  val: 0
parse_dataset:
  filtering: all
  threshold: 0.5
