name: graphpli

channels:
  - pyg
  - pytorch
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - pytorch=1.10.1
  - pytorch-lightning=1.5.8
  - pytorch-cluster=1.5.9
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.12
  - pytorch-spline-conv=1.2.1
  - rdkit=2020.09.5
  - gitpython=3.1.26
  - setuptools=58.0.4
  - rich=12.3.0
  - pip:
      - torch-geometric==2.1.0
      - glycowork==0.5.0
      - fair-esm==2.0.0
      - glyles==0.5.0
      - scikit-learn==1.0.2
      - wandb==0.12.1
