seed: 42
name: leor_ict_esm2
datamodule:
  filename: ./prebuild/leor/results/elnwIntanc_6f82b67b.pkl
  exp_name: thesis
  batch_size: 64
  num_workers: 14
trainer:
  gpus: 1
  max_epochs: 150
  profiler: null
  gradient_clip_val: 100
checkpoints:
  monitor: val_BinaryAccuracy
  save_top_k: 3
  mode: max
model:
  feat_method: concat
  monitor: val_loss
  drug:
    hidden_dim: 128
    method: sweetnet
  prot:
    hidden_dim: 128
    method: pickle
    file: ./prebuild/esm_embeds/Lectins_ESM2.pkl
  mlp:
    dropout: 0.2
    hidden_dim: 512
    num_layers: 3
  optimizer:
    module: adam
    lr: 0.0001
    weight_decay: 0.01
    momentum: 0.01
    lr_schedule:
      module: lwca
      monitor: val_loss
      cos_restart_dist: 50
      warmup_epochs: 25
      min_lr: 1e-7
      start_lr: 1e-5
