seed: 42
name: dti_base_reg
datamodule:
  filename: /scratch/SCRATCH_SAS/roman/GraphPLI/glycowork_4_700_cut/results/prepare_all/rlnwgnrisarn_393b2a65.pkl
  add_test:
    unilectin: /scratch/SCRATCH_SAS/roman/GraphPLI/unilectin/results/prepare_all/rlnwgnranc_10a4630c.pkl
  exp_name: two_ds
  batch_size: 64
  num_workers: 14
trainer:
  devices: -1
  max_epochs: 150
  profiler: null
  gradient_clip_val: 100
checkpoints:
  monitor: val/loss
  save_top_k: 3
  mode: min
model:
  feat_method: concat
  monitor: val/loss
  drug:
    hidden_dim: 256
    method: graph
    node:
      module: ginconv
      dropout: 0.1
      hidden_dim: 256
      num_layers: 3
    pool:
      module: mean
  prot:
    hidden_dim: 256
    method: graph
    node:
      module: ginconv
      dropout: 0.1
      hidden_dim: 256
      num_layers: 3
    pool:
      module: mean
  mlp:
    dropout: 0.2
    hidden_dim: 256
    num_layers: 2
  optimizer:
    module: adam
    lr: 0.0001
    weight_decay: 0.01
    momentum: 0.01
    lr_schedule:
      module: lwca
      monitor: val/loss
      cos_restart_dist: 50
      warmup_epochs: 25
      min_lr: 1e-7
      start_lr: 1e-5
